### ISSUE TITLE
Can't treat NumberInt

### ISSUE THREAD

**Issue by thaim** [rwynn/mongofluxd#1]
I'm trying to sync data which contains type: NumberInt.
But error occurred while sync data.

Create data:

    for (var i=0; i<100; ++i) { sleep(1); var t = new Date(); db.number_int.insert({n: NumberInt("1"),  t: t}); }

Error message:

    ERROR 2018/04/16 23:32:50 Unsupported type int for field n in namespace reproduce.number_int

**Comment by thaim** [comment]
Thank you for your quick response.
This works fine for me.

**Comment by rwynn** [comment]
Thanks for reporting it.
