### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [rwynn/mongofluxd#2]
Hello @rwynn 

I am designing logos to support open source software. I have designed a logo for mongofluxd software. ı combined the mongodb and  the influxdb logo. If you like it, I'll send a pr. Please tell me what you think of it. I will wait for feedback.

have a nice day!

![mongo](https://user-images.githubusercontent.com/36298335/45882877-23612000-bdb8-11e8-9964-5ab93ee05b11.jpg)

**Comment by rwynn** [comment]
Hi there - this is a really nice logo but I’m not sure this project is able to use it due to restrictions. 

https://www.mongodb.com/brand-resources
