### ISSUE TITLE
Allow generate measure name from a db field

### ISSUE THREAD

**Issue by elbandi** [rwynn/mongofluxd#4]
We have two fields in mongo db, and want to save data based on this fields:

`{
  "base": "btc",
  "coin": "ltc",
...
}`

save to "btc_ltc" measure.

There is two possible soluton:
 - plugin generate the point name, and use that name in newPoint (
`pt, err := client.NewPoint(pt.Name, pt.Tags, pt.Fields, pt.Timestamp)`
- measure settings allow an array/expression/dontknow, and generate the name:
`measure = "{coin}_{base}"`  -> name: "btc_ltc" (ofc, error if field is missing)

I prefer second solution (thats backward compatible)
any opinion?

**Comment by rwynn** [comment]
Hi @Elbandi with latest in master you should just be able to use the following syntax (go template):

```
[[measurement]]
measure = "{{.Fields.base}}_{{.Fields.coin}}"
```
If coin and base are tags instead of fields then use:

```
[[measurement]]
measure = "{{.Tags.base}}_{{.Tags.coin}}"
```

If you have a dot in the field or tag name (nested field in MongoDB) then you would need to use this syntax:

```
[[measurement]]
measure = "{{index .Tags "my.base"}}_{{index .Tags "my.coin"}}"
```

**Comment by elbandi** [comment]
Sorry for long delay, i'm a little busy. I testing the new code, but there is an issue:
If i want to use this template syntax, i have to add the "coin" or "base" to tags (or fields) list. After that, measure name resolve works, but the series has a new tags (which is redundant with series name):

    show series;
    ....
    ltc_btc,base=btc,coin=ltc,...
    ....

i dont need that tags. I try to solve this: add a new datastore as "Other", and store this unwanted tags there, and in templatestring i can use _.Other.base_ Is there a better solution/idea for this?

**Comment by rwynn** [comment]
yeah you could add another key, e.g. `Other` (I would call it `Doc` or `Data` personally), that stores the whole document from MongoDB (via op.Data).

**Comment by rwynn** [comment]
@Elbandi you should now be able to access any field from MongoDB as 

```
[[measurement]]
measure = "{{.Doc.base}}_{{.Doc.coin}}"
```

Even if you don't add those as fields or tags.
